from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider
import json

# This secure connect bundle is autogenerated when you download your SCB, 
# if yours is different update the file name below
cloud_config= {
  'secure_connect_bundle': 'secure-connect-ex-aval4.zip'
}

# This token JSON file is autogenerated when you download your token, 
# if yours is different update the file name below
with open("ex_aval4-token.json") as f:
    secrets = json.load(f)

CLIENT_ID = secrets["clientId"]
CLIENT_SECRET = secrets["secret"]

auth_provider = PlainTextAuthProvider(CLIENT_ID, CLIENT_SECRET)
cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
session = cluster.connect()

row = session.execute("select release_version from system.local").one()
if row:
  print(row[0])
else:
  print("An error occurred.")

session.set_keyspace('ksstock')

#QUERY CARRO CONSULTAS
carro_desejado = input("Digite o carro que deseja consultar: ")

result = session.execute(f"SELECT (nome, estante, quantidade) FROM estoque WHERE carro = '{carro_desejado}' ALLOW FILTERING;")

if result is not None:
   print("Sucesso!")
   print(result)
else:
   print("Falha catastrofica")